export const Images = {
    leading1: require("../assets/Leading1.png"),
    leading2: require("../assets/Leading2.png"),
    leading3: require("../assets/Leading3.png"),
    leading1Back: require("../assets/Leading1Back.png"),
    signIn: require("../assets/Signin.png"),
    signupLine: require("../assets/SignupLine.png"),
    signupLine1: require("../assets/SignupLine1.png"),
    facebookLogo: require("../assets/Facbook.png"),
    googleLogo: require("../assets/Googlelogo.png"),
    apple: require("../assets/Group.png"),
    homeCall: require("../assets/HomeCall.png"),
    homeHeart: require("../assets/HomeHeart.png"),
    homeCart: require("../assets/HomeCart.png"),
    homeSearch: require("../assets/HomeSearch.png"),
    homeScan: require("../assets/HomeScane.png"),
    homeCamera: require("../assets/HomeCamera.png"),
    home: require("../assets/Home.png"),
    homeCalender: require("../assets/HomeCalender.png"),
    homeChat: require("../assets/HomeChat.png"),
    homeBanner: require("../assets/HomeBanner.png"),
    homeVision1: require("../assets/Vision1.png"),
    homeVision2: require("../assets/Vision2.png"),
    homeVision3: require("../assets/Vision3.png"),
    homeVision4: require("../assets/Vision4.png"),
    cele1: require("../assets/cele1.png"),
    cele2: require("../assets/cele2.png"),
    cele3: require("../assets/cele3.png"),
    cele4: require("../assets/cele1.png"),
    pre1: require("../assets/pre1.png"),
    pre2: require("../assets/pre2.png"),
    pre3: require("../assets/pre3.png"),
    homeHoliday: require("../assets/HomeHoliday.png"),
    eyeTest: require("../assets/EyeTest.png"),
    backIcon: require("../assets/BackIcon.png"),
    jacobs1: require("../assets/Jacobs1.png"),
    jacobs2: require("../assets/Jacobs2.png"),
    jacobs3: require("../assets/Jacobs3.png"),
    jacobs4: require("../assets/Jacobs4.png"),
    jacobs5: require("../assets/Jacobs5.png"),
    jacobs6: require("../assets/Jacobs6.png"),
    bestSeller: require("../assets/BestSeller.png"),
    ratingStar: require("../assets/Rating.png"),
    heart: require("../assets/HeartBlue.png"),
    filter: require("../assets/Filter.png"),
    blackHeart: require("../assets/BlackHeart.png"),
    shareIcon: require("../assets/Share.png"),
    whiteStar: require("../assets/WhiteStar.png"),
    detailWidth: require("../assets/DetailWidth.png"),
    frameWeight: require("../assets/FrameWeight.png"),
    frameWarrenty: require("../assets/FrameWarrenty.png"),
    frameReturn: require("../assets/FrameReturn.png"),
    frameSpecification: require("../assets/FrameSpecification.png"),
    address: require("../assets/Address.png"),
    locationBlue: require("../assets/LocationBlue.png"),
    spectDetailsBen: require("../assets/SpectDetailBen.png"),
    reviewProfile: require("../assets/ReviewProfile.png"),
    redClose: require("../assets/RedClose.png"),
    whiteRight: require("../assets/WhiteRight.png"),
    dottedLine: require("../assets/DottedLine.png"),
    googlePay: require("../assets/GooglePay.png"),
    upiLogo: require("../assets/UPILogo.png"),
    downArrow: require("../assets/DownArrow.png"),
    debitCard: require("../assets/Debitcard.png"),
    hdfcbank: require("../assets/HdfcBank.png"),
    sbiBank: require("../assets/SbiBank.png"),
    icicibank: require("../assets/IciciBank.png"),
    profile: require("../assets/Profile.png"),
    orderBox: require("../assets/OrderBox.png"),
    heartOutline: require("../assets/BlackHeartOutline.png"),
    wallet: require("../assets/Wallet.png"),
    rightArrow: require("../assets/RightArrow.png"),
    settingHome: require("../assets/SettingHome.png"),
    settingNotification: require("../assets/Notification.png"),
    settingFaq: require("../assets/Faq.png"),
    settingAbout: require("../assets/AboutUs.png"),
    settingHelp: require("../assets/Help.png"),
    settingLogout: require("../assets/Logout.png"),
    shutDown: require("../assets/shutdown.png"),
    forgotPassword: require("../assets/ForgotPassword.png"),
    otpImage: require("../assets/OtpImage.jpg"),
    aviatorGlass : require("../assets/AviatorGlass.png"),
    catGlass : require("../assets/CatGlass.png"),
    geometricGlass : require("../assets/GeometricGlass.png"),
    ovalGlass : require("../assets/OvalGlass.png"),
    rectangleGlass : require("../assets/RectangleGlass.png"),
    roundGlass : require("../assets/RoundGlass.png"),
    wishlistSearch : require("../assets/WishlistSearch.png"),
    wishlistData1: require("../assets/WishlistData1.png"),
    wishlistData2: require("../assets/WishlistData2.png"),
    wishlistData3: require("../assets/WishlistData3.png"),
    wishlistData4: require("../assets/WishlistData4.png"),
    wishlistDelete : require("../assets/WishlistDelete.png"),
    blackHome : require("../assets/BlackHome.png"),
    whiteHome : require("../assets/WhiteHome.png"),
    blackWork : require("../assets/BlackWork.png"),
    whiteWork : require("../assets/WhiteWork.png"),
    blackFillHeart : require("../assets/BlackFillHeart.png"),
    whiteFillHeart : require("../assets/WhiteHeart.png"),
    blackLocation : require("../assets/BlackLocation.png"),
    whiteLocation : require("../assets/WhiteLocation.png"),
    addressUser : require("../assets/AddressUser.png"),
    addressCall : require("../assets/AddressCall.png"),
    frameDetails: require("../assets/FrameDetails.png"),
    orderFilter: require("../assets/OrderSearch.png"),
    offer1: require("../assets/Offer1.png"),
    offer2: require("../assets/Offer2.png"),
    offer3: require("../assets/Offer3.png"),
    offer4: require("../assets/Offer4.png"),
    offer5: require("../assets/Offer5.png"),
    orderDeliver: require("../assets/OrderDeliver.png"),
    orderPending: require("../assets/OrderPending.png"),
    orderCancel: require("../assets/OrderCancel.png"),
    EyesGlass: require("../assets/EyeGlasses.png"),
    contactLens: require("../assets/ContactLens.png"),
    sunsGlass: require("../assets/SunGlasses.png"),
    PowerGlass: require("../assets/PowerSunglass.png"),
    zeroPowerGlass: require("../assets/ZeroPower.png"),
    exploreImage: require("../assets/ExploreMain.png"),
    wayfarerImage: require("../assets/WayfarerGlass.png"),
    aviatorImage: require("../assets/AviatorGlass2.png"),
    rectangleImage: require("../assets/RectangleGlass2.png"),
    geometricImage: require("../assets/GeometricGlass2.png"),
    rimlessImage: require("../assets/RimlessGlass.png"),
    halfRimImage: require("../assets/HalfRim.png"),
    dummyProfile: require("../assets/DummyProfile.png"),
    editIcon: require("../assets/EditIcon.png"),
}